### ISSUE TITLE
Display gzipped size as an option

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/pr-bot#11]
When reviewing PRs, it's great being able to see the size of production builds. It would also be nice to see an estimate of the gzipped size of these builds.

e.g if LogHelper.js increases by 2KB that's good to know.

What is the real impact this has on the final bundle that is likely to get deployed after gzip? 

Perhaps this would make sense as an extra column.

![image](https://user-images.githubusercontent.com/110953/29181852-89ed72f8-7db1-11e7-8ef9-578f5bdc66f5.png)

**Comment by gauntface** [comment]
We can use https://www.npmjs.com/package/gzip-size for this. Probably add it as an option and turn it on by default (assuming most people are worried about browser size).
