### ISSUE TITLE
Don't display decimal places for Bytes or Percentages

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/pr-bot#13]
@gauntface: Are you open to a PR that will remove the decimal places when outputting Bytes (we don't have to worry about fractional bytes, thankfully...) and Percentages (which don't have to be *that* accurate)?

I feel like it would clean up the display a bit.

**Comment by gauntface** [comment]
Yeah please do. I'm going to warm you that the tests and code for that are not great, I just got it working and it's overdue a refactor so feel free to do any PR on this I just apologise in advance
