### ISSUE TITLE
README: include a screenshot of the output near the top

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/pr-bot#8]
When a perspective user lands on the repo, it would be good to quickly and early on show them a visual of what the pr-bot can enable on their PRs. Just a screenshot would do the trick. Perhaps above the getting started.

**Comment by gauntface** [comment]
I added two screenshots, one of the PR output and one for the console output.

Would you move the position of it anywhere?

**Comment by addyosmani** [comment]
Nice! I'd see about including one like 

![](https://camo.githubusercontent.com/7e446cfe82e32ced356568294afb8133b57cb8cc/687474703a2f2f692e696d6775722e636f6d2f6f5a50726458722e706e67) - maybe expanding the details tag too? above getting started.
